//! `metaphor compose generate` — merge per-project `compose.fragment.yml`
//! files into a workspace-level `docker-compose.yml`.
//!
//! Each project declares its service body (image/build/volumes/env) in
//! `<project>/compose.fragment.yml`; this command reads `metaphor.yaml`,
//! pulls in each fragment, injects the service name (from `Project.name`),
//! and emits the merged document. Dry-run by default.

use anyhow::{bail, Context, Result};
use metaphor_workspace::{Manifest, Project};
use serde_yaml::{Mapping, Value};
use std::fs;
use std::path::{Path, PathBuf};

pub const FRAGMENT_FILE: &str = "compose.fragment.yml";
pub const DEFAULT_OUTPUT: &str = "docker-compose.yml";

pub struct ComposeOptions<'a> {
    pub output: &'a Path,
    pub dry_run: bool,
}

pub fn cmd_compose_generate(
    manifest: &Manifest,
    workspace_root: &Path,
    opts: &ComposeOptions<'_>,
) -> Result<()> {
    let mut services = Mapping::new();
    let mut missing: Vec<String> = Vec::new();

    for p in &manifest.projects {
        let fragment_path = p.resolved_path(workspace_root).join(FRAGMENT_FILE);
        if !fragment_path.exists() {
            missing.push(p.name.clone());
            continue;
        }
        let body = load_fragment(&fragment_path, p)?;
        services.insert(Value::String(p.name.clone()), body);
    }

    if services.is_empty() {
        bail!(
            "no projects declared a {} — add one per project to make compose generate useful",
            FRAGMENT_FILE
        );
    }

    let mut doc = Mapping::new();
    doc.insert(Value::String("services".into()), Value::Mapping(services));
    let yaml = serde_yaml::to_string(&Value::Mapping(doc))
        .context("serializing merged compose document")?;
    let banner =
        format!("# Generated by `metaphor compose generate`. Do not edit — rerun instead.\n");
    let full = format!("{banner}{yaml}");

    if opts.dry_run {
        println!("{full}");
        if !missing.is_empty() {
            eprintln!(
                "note: {} project(s) without {}: {}",
                missing.len(),
                FRAGMENT_FILE,
                missing.join(", ")
            );
        }
        println!(
            "(dry run — pass --write to write to {})",
            opts.output.display()
        );
    } else {
        fs::write(opts.output, &full)
            .with_context(|| format!("writing {}", opts.output.display()))?;
        println!(
            "Wrote {} ({} service{})",
            opts.output.display(),
            manifest.projects.len() - missing.len(),
            if manifest.projects.len() - missing.len() == 1 {
                ""
            } else {
                "s"
            }
        );
        if !missing.is_empty() {
            println!(
                "skipped {} project(s) without {}: {}",
                missing.len(),
                FRAGMENT_FILE,
                missing.join(", ")
            );
        }
    }
    Ok(())
}

fn load_fragment(path: &Path, project: &Project) -> Result<Value> {
    let raw = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let parsed: Value =
        serde_yaml::from_str(&raw).with_context(|| format!("parsing {}", path.display()))?;
    // A fragment is the *service body* (image/build/volumes/…). We refuse
    // fragments that already wrap in `services:` — that's a merge conflict
    // we don't resolve.
    if let Value::Mapping(ref m) = parsed {
        if m.contains_key(&Value::String("services".into())) {
            bail!(
                "{} for '{}' contains a top-level `services:` key — fragments are the service body, not a full compose file",
                path.display(),
                project.name
            );
        }
    }
    if !matches!(&parsed, Value::Mapping(_)) {
        bail!(
            "{} for '{}' must be a YAML mapping",
            path.display(),
            project.name
        );
    }
    Ok(parsed)
}

pub fn default_output(workspace_root: &Path) -> PathBuf {
    workspace_root.join(DEFAULT_OUTPUT)
}

#[cfg(test)]
mod tests {
    use super::*;
    use metaphor_workspace::{ProjectType, CURRENT_VERSION};
    use tempfile::TempDir;

    fn proj(name: &str) -> Project {
        Project {
            name: name.into(),
            project_type: ProjectType::BackendService,
            path: format!("./{name}"),
            remote: None,
            git_ref: None,
            depends_on: vec![],
        }
    }

    #[test]
    fn merges_fragments_into_services() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir(tmp.path().join("api")).unwrap();
        fs::write(
            tmp.path().join("api").join(FRAGMENT_FILE),
            "image: myorg/api:dev\nports: ['8080:8080']\n",
        )
        .unwrap();
        let m = Manifest {
            version: CURRENT_VERSION,
            projects: vec![proj("api")],
        };
        let out = tmp.path().join("out.yml");
        cmd_compose_generate(
            &m,
            tmp.path(),
            &ComposeOptions {
                output: &out,
                dry_run: false,
            },
        )
        .unwrap();
        let body = fs::read_to_string(&out).unwrap();
        assert!(body.contains("services:"));
        assert!(body.contains("api:"));
        assert!(body.contains("myorg/api:dev"));
    }

    #[test]
    fn rejects_fragment_with_services_key() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir(tmp.path().join("api")).unwrap();
        fs::write(
            tmp.path().join("api").join(FRAGMENT_FILE),
            "services:\n  api:\n    image: x\n",
        )
        .unwrap();
        let m = Manifest {
            version: CURRENT_VERSION,
            projects: vec![proj("api")],
        };
        let out = tmp.path().join("out.yml");
        let err = cmd_compose_generate(
            &m,
            tmp.path(),
            &ComposeOptions {
                output: &out,
                dry_run: false,
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("top-level `services:`"));
    }

    #[test]
    fn skips_projects_without_fragment() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir(tmp.path().join("api")).unwrap();
        fs::write(
            tmp.path().join("api").join(FRAGMENT_FILE),
            "image: api:dev\n",
        )
        .unwrap();
        fs::create_dir(tmp.path().join("no-fragment")).unwrap();
        // no fragment file
        let m = Manifest {
            version: CURRENT_VERSION,
            projects: vec![proj("api"), proj("no-fragment")],
        };
        let out = tmp.path().join("out.yml");
        cmd_compose_generate(
            &m,
            tmp.path(),
            &ComposeOptions {
                output: &out,
                dry_run: false,
            },
        )
        .unwrap();
        let body = fs::read_to_string(&out).unwrap();
        assert!(body.contains("api:"));
        assert!(!body.contains("no-fragment:"));
    }
}
